# Generated by Django 3.2 on 2022-08-28 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='auction_name',
            new_name='title',
        ),
    ]
