# Generated by Django 3.2 on 2022-08-28 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_rename_auction_name_auction_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auction',
            name='starting_bid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
