# Generated by Django 3.2 on 2022-08-28 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_auto_20220828_2220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='price',
            new_name='cur_price',
        ),
    ]
