# Generated by Django 3.2 on 2022-08-29 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0005_auction_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='saller',
        ),
    ]
