# Generated by Django 3.2 on 2022-08-29 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0006_remove_auction_saller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='comment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
